name: Provision DMX Core
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    env:
      AzureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTIONID }}
      AzureTenantId: ${{ secrets.AZURE_TENANTID }}
      AzureAdAppProvisionClientId: ${{ secrets.AZURE_ADAPP_PROVISION_CLIENTID }}
      AzureAdAppProvisionClientSecret: ${{ secrets.AZURE_ADAPP_PROVISION_CLIENTSECRET }}
      AzureAdAppDmxCoreClientId: ${{ secrets.AZURE_ADAPP_DMXCORE_CLIENTID }}
      AzureAdAppDmxCoreInstance: ${{ secrets.AZURE_ADAPP_DMXCORE_INSTANCE }}
      AzureAdAppDmxCoreDomain: ${{ secrets.AZURE_ADAPP_DMXCORE_DOMAIN }}
      AzureAdAppDmxCoreCallbackPath: ${{ secrets.AZURE_ADAPP_DMXCORE_CALLBACKPATH }}
      AzureAdAppDmxCoreScopesGetAllLabs: ${{ secrets.AZURE_ADAPP_DMXCORE_SCOPES_GETALLLABS }}
      AzureAdAppDmxCoreScopesPostLab: ${{ secrets.AZURE_ADAPP_DMXCORE_SCOPES_POSTLAB }}
      AzureAdAppDmxCoreScopesDeleteLab: ${{ secrets.AZURE_ADAPP_DMXCORE_SCOPES_DELETELAB }}
      AzureAdAppDmxCoreScopesPostLabCommand: ${{ secrets.AZURE_ADAPP_DMXCORE_SCOPES_POSTLABCOMMAND }}
      AzureAdAppDmxCoreScopesGetLabCommand: ${{ secrets.AZURE_ADAPP_DMXCORE_SCOPES_GETLABCOMMAND }}
      AzureAdAppDmxCoreScopesPutLabCommand: ${{ secrets.AZURE_ADAPP_DMXCORE_SCOPES_PUTLABCOMMAND }}
      AzureSqlServerAdminName: ${{ secrets.AZURE_SQLSERVER_ADMINNAME }}
      AzureSqlServerAdminAccess: ${{ secrets.AZURE_SQLSERVER_ADMINACCESS }}
      AzureAppServiceExternalLabApiUrl: ${{ secrets.AZURE_APPSERVICE_EXTERNALLABAPI_URL }}
      AzureAppServiceExternalLabApiAccessKey: ${{ secrets.AZURE_APPSERVICE_EXTERNALLABAPI_ACCESSKEY }}
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Provision
      run: dotnet run --project .\DMX.Core.Api.Infrastructure.Provision\DMX.Core.Api.Infrastructure.Provision.csproj
